# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' mvrnormArma
#'
#' This function returns n samples of multivariate normal distribution with mean mu and variance Sigma.
#'
#' @param n Sample size
#' @param mu Mean vector
#' @param Sigma Variance-covariance matrix
#' @export
mvrnormArma <- function(n, mu, Sigma) {
    .Call('_diffNet_mvrnormArma', PACKAGE = 'diffNet', n, mu, Sigma)
}

solve_tmp_c <- function(x) {
    .Call('_diffNet_solve_tmp_c', PACKAGE = 'diffNet', x)
}

#' get_score_c
#'
#' This function returns the score statistic between y1 and y2 against one-dimensional covariate x
#' The returned score statistic is not adjusted for sample size
#'
#' @param x Covariate vector
#' @param y1 variable 1
#' @param y2 variable 2
#' @export
get_score_c <- function(x, y1, y2) {
    .Call('_diffNet_get_score_c', PACKAGE = 'diffNet', x, y1, y2)
}

#' get_score_w_c
#'
#' This function takes the sum of two variables, w, and one dimensional covariate x
#' and returns the score test statistic
#'
#' @param x Covariate vector
#' @param w sum of variable1 and variable2
#' @export
get_score_w_c <- function(x, w) {
    .Call('_diffNet_get_score_w_c', PACKAGE = 'diffNet', x, w)
}

#' get_score_W_c
#'
#' This function returns a vector of score statistics from one dimensional covariate x and coexpression matrix W
#' W should be in the form of (y1+y2, y1+y3, ... y1+yK)
#' The function returns K-1 scores for each pair
#'
#' @param x Covariate vector
#' @param W Sums for each pairs of variables
#' @export
get_score_W_c <- function(x, W) {
    .Call('_diffNet_get_score_W_c', PACKAGE = 'diffNet', x, W)
}

#' get_degree_c
#'
#' This function returns a sum statistic d for vector y tested with all other variables in matrix Y against covariate x
#'
#' @param x Covariate vector
#' @param y Variable of interest
#' @param Y All other variables to test with y
#' @export
get_degree_c <- function(x, y, Y) {
    .Call('_diffNet_get_degree_c', PACKAGE = 'diffNet', x, y, Y)
}

#' get_degree_c
#'
#' This function returns a sum statistic d for vector y tested with all other variables in matrix Y against covariate x
#'
#' @param x Covariate vector
#' @param W Matrix of [y1+y2, y1+y3, .., y1+yK] to get degree of y1
#' @export
get_degree_w_c <- function(x, W) {
    .Call('_diffNet_get_degree_w_c', PACKAGE = 'diffNet', x, W)
}

#' @export
get_eta_c <- function(rho12, rho23, rho13) {
    .Call('_diffNet_get_eta_c', PACKAGE = 'diffNet', rho12, rho23, rho13)
}

#' @export
dgenrayleigh_c <- function(t, alpha, beta, logg = FALSE) {
    .Call('_diffNet_dgenrayleigh_c', PACKAGE = 'diffNet', t, alpha, beta, logg)
}

#' @export
cgenrayleigh_c <- function(t, alpha, beta, logg = FALSE) {
    .Call('_diffNet_cgenrayleigh_c', PACKAGE = 'diffNet', t, alpha, beta, logg)
}

#' @export
get_H_c <- function(Sigma) {
    .Call('_diffNet_get_H_c', PACKAGE = 'diffNet', Sigma)
}

#' @export
get_A1_c <- function(k, p, TT, RR, n) {
    .Call('_diffNet_get_A1_c', PACKAGE = 'diffNet', k, p, TT, RR, n)
}

#' @export
get_A2_c <- function(k, p, TT, RR, n) {
    .Call('_diffNet_get_A2_c', PACKAGE = 'diffNet', k, p, TT, RR, n)
}

#' @export
get_A3_c <- function(k, p, TT, RR, n) {
    .Call('_diffNet_get_A3_c', PACKAGE = 'diffNet', k, p, TT, RR, n)
}

#' @export
get_TT_RR_c <- function(A) {
    .Call('_diffNet_get_TT_RR_c', PACKAGE = 'diffNet', A)
}

#' small_sample_correction_c
#'
#' This function returns a sum statistic d for vector y tested with all other variables in matrix Y against covariate x
#'
#' @param x Covariate vector
#' @param C chi-squared threshold for desired FDR rate
#' @param k number of covariates + 1
#' @param p number of covariates + 1
#' @export
small_sample_correction_c <- function(x, C, k, p = 2L) {
    .Call('_diffNet_small_sample_correction_c', PACKAGE = 'diffNet', x, C, k, p)
}

#' @export
cubic_correction_c <- function(x, C, k, p) {
    .Call('_diffNet_cubic_correction_c', PACKAGE = 'diffNet', x, C, k, p)
}

#' @export
cubic_coeff_c <- function(A, C, k, p) {
    .Call('_diffNet_cubic_coeff_c', PACKAGE = 'diffNet', A, C, k, p)
}

#' simulate_c
#'
#' Given fixed covariate and covariance matrix, this function simulates multivariate normal Y
#' and returns the score vector for each variable
#'
#' @param x Covariate vector
#' @param Sigma true covariance matrix of matrix Y
#' @param use_Hhat Boolean argument whether to use true Sigma or estimate Sigma
#' @export
simulate_c <- function(x, Sigma, use_Hhat = TRUE) {
    .Call('_diffNet_simulate_c', PACKAGE = 'diffNet', x, Sigma, use_Hhat)
}

#' @export
shuffle_x_c <- function(x, B) {
    .Call('_diffNet_shuffle_x_c', PACKAGE = 'diffNet', x, B)
}

#' @export
store_W_c <- function(y, smallY) {
    .Call('_diffNet_store_W_c', PACKAGE = 'diffNet', y, smallY)
}

#' bootstrap_c
#'
#' This function performs permutation test for given covariate x B times
#' Also takes as input W instead of Y matrix
#'
#' @param x Covariate vector
#' @param B number of permutations
#' @param W transformed variable matrix
#' @export
bootstrap_c <- function(x, B, W) {
    .Call('_diffNet_bootstrap_c', PACKAGE = 'diffNet', x, B, W)
}

